import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import styled from 'styled-components'
import HeaderRody from '../components/home/Header'
import HeaderOption2 from '../components/home/Header2'
import PresentationRody from '../components/home/Presentation'
import Carrousel from '../components/home/Carrousel'
import PresentationValues from '../components/home/PresentationValues'
import OurObjetive from '../components/home/OurObjetive'
import OurServices from '../components/home/OurServices'
import Sentences from '../components/home/Sentences'
import Information from '../components/home/Information'
import Footer from '../components/home/Footer'




export default function Home() {
  return (
    <div className="container-fluid" style={{paddingLeft: "0px", paddingRight: "0px"}}>
      <Head>
        <title>RODY</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossOrigin="true"></link>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Bangers&display=swap" rel="stylesheet"></link>
      </Head>
      
      <HeaderOption2 />
      <PresentationRody />
      <Carrousel />
      <PresentationValues />
      <OurObjetive />
      <OurServices />
      <Sentences />
      <Information />
      <Footer />
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossOrigin="anonymous"></script>
    </div>
  )
}
